"""Telegram command handlers — re-export facade.

The actual implementations live in:

- `session_handlers` — `/start`, `/play`, `/stop`, `/hint`,
  `/skip`, answer handlers
- `word_handlers` — `/addword`, `/mywords`, `/deleteword`
- `stats_handlers` — `/stats`, `/weak`
"""

from rembrandt_chat.session_handlers import (
    PLAY_CAT_PREFIX,
    PLAY_LANG_PREFIX,
    PLAY_MODE_PREFIX,
    PLAY_TOPIC_PREFIX,
    handle_answer_callback,
    handle_answer_text,
    handle_category_callback,
    handle_language_callback,
    handle_play_category,
    handle_play_language,
    handle_play_topic,
    handle_topic_callback,
    handle_play_mode,
    help_command,
    hint,
    language,
    topics,
    play,
    review,
    skip,
    start,
    stop,
)
from rembrandt_chat.stats_handlers import (
    AWAITING_FILE,
    export_progress,
    forecast,
    history,
    import_cancel,
    import_file,
    import_start,
    reminders,
    retention,
    stats,
    weak,
)
from rembrandt_chat.word_handlers import (
    AWAITING_DEFINITION,
    AWAITING_TAGS,
    AWAITING_WORD,
    addword_cancel,
    addword_definition,
    addword_skip_tags,
    addword_start,
    addword_tags,
    addword_word,
    deleteword,
    handle_deleteword_callback,
    mywords,
    search,
)

__all__ = [
    "PLAY_CAT_PREFIX",
    "PLAY_LANG_PREFIX",
    "PLAY_MODE_PREFIX",
    "PLAY_TOPIC_PREFIX",
    "start",
    "help_command",
    "play",
    "review",
    "language",
    "handle_category_callback",
    "handle_language_callback",
    "handle_play_category",
    "handle_play_language",
    "handle_play_topic",
    "handle_play_mode",
    "topics",
    "handle_topic_callback",
    "stop",
    "hint",
    "skip",
    "handle_answer_text",
    "handle_answer_callback",
    "AWAITING_WORD",
    "AWAITING_DEFINITION",
    "AWAITING_TAGS",
    "addword_start",
    "addword_word",
    "addword_definition",
    "addword_tags",
    "addword_skip_tags",
    "addword_cancel",
    "mywords",
    "deleteword",
    "search",
    "handle_deleteword_callback",
    "stats",
    "weak",
    "forecast",
    "retention",
    "history",
    "reminders",
    "export_progress",
    "AWAITING_FILE",
    "import_start",
    "import_file",
    "import_cancel",
]
